

spring:
  ai:
    llm-proxy:
      client:
        options:
          hostname: localhost
          port: ${server.grpc.port}
    openai:
      api-key: demo # SPRING_AI_OPENAI_API_KEY
      chat:
        options:
          stream-usage: true

server:
  grpc:
    port: 50051

